DEV_LIVE_SERVER_URL: 'localhost'
DEV_LIVE_SERVER_USER: 'suhanlee'
DEV_LIVE_SERVER_PASSWORD: 'game1234'


LIVE_SERVER_URL: '192.168.0.6'
LIVE_SERVER_USER: 'suhanlee'
LIVE_SERVER_PASSWORD: 'game1234'


PRD_LIVE_SERVER_URL: 'url'
PRD_LIVE_SERVER_USER: 'prd_server_address'
PRD_LIVE_SERVER_PASSWORD: 'password'
